/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * user guide available at https://docs.gradle.org/5.0/userguide/tutorial_java_projects.html
 */


import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    // Apply the java plugin to add support for Java
    //java

    // Apply the application plugin to add support for building an application
    //application


    kotlin("jvm") version "1.3.11"
   id("com.github.johnrengelman.shadow") version "2.0.4"

}

   // mainClassName = "HelloSeleniumWorld.App"


repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
 mavenCentral()
}

dependencies {

 compile (group= "org.seleniumhq.selenium", name = "selenium-java", version = "3.+" )

    // This dependency is found on compile classpath of this component and consumers.
    implementation("com.google.guava:guava:26.0-jre")

    // Use TestNG framework, also requires calling test.useTestNG() below
    testImplementation("org.testng:testng:6.14.3")
}

//application {
    // Define the main class for the application
  //  mainClassName = "HelloSeleniumWorld.App"
//}

val test by tasks.getting(Test::class) {
    // Use TestNG for unit tests
    useTestNG()
}

tasks.withType<ShadowJar> {

    baseName = "app"
    classifier = "demo"
    version = "1"


    manifest.attributes.apply {
        put("Implementation-Title", "Gradle Jar File Example")
        //put("Implementation-Version" version)
        put("Main-Class", "HelloSeleniumWorld.App")
    }

}